services:
  playwright-mcp:
    build: .
    container_name: playwright-mcp-server
    tty: true
    env_file:
      - .env
    environment:
      # MCP server configuration
      - MCP_PORT=${MCP_HOST_PORT:-9222}
      # VNC server configuration
      - VNC_PASSWORD=${VNC_PASSWORD:-browser-use}
      - VNC_DISPLAY=${VNC_DISPLAY:-:1}
      - VNC_PORT=${VNC_PORT:-5901}
      - VNC_GEOMETRY=${VNC_GEOMETRY:-1920x1080}
      - VNC_DEPTH=${VNC_DEPTH:-24}
      # noVNC proxy configuration
      - NOVNC_PORT=${NOVNC_PORT:-8080}
    ports:
      # MCP server port
      - "${MCP_HOST_PORT:-9222}:${MCP_HOST_PORT:-9222}"
      # VNC server port
      - "${VNC_PORT:-5901}:${VNC_PORT:-5901}"
      # noVNC web interface port
      - "${NOVNC_PORT:-8080}:8080"
    restart: unless-stopped
